protected/models/Bank.php
<?php

/**
 * This is the model class for table "Bank".
 *
 * The followings are the available columns in table 'Bank':
 * @property integer $id
 * @property string $nama_bank
 * @property string $pemilik
 * @property string $no_rek
 * @property string $logo
 */
class Bank extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'Bank';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nama_bank, pemilik, logo,no_rek', 'required'),
			array('nama_bank, pemilik, no_rek, logo', 'length', 'max'=>100),
			array('logo','file','types'=>'jpg, gif, png', 'allowEmpty'=>true),			
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, nama_bank, pemilik, no_rek, logo', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nama_bank' => 'Nama Bank',
			'pemilik' => 'Pemilik',
			'no_rek' => 'No Rek',
			'logo' => 'Logo',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nama_bank',$this->nama_bank,true);
		$criteria->compare('pemilik',$this->pemilik,true);
		$criteria->compare('no_rek',$this->no_rek,true);
		$criteria->compare('logo',$this->logo,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Bank the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/BankController.php
<?php

class BankController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin_page';
	const URLUPLOAD='/../images/bank/';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		isAuth::Admin();
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		isAuth::Admin();

		$model=new Bank;
		if(isset($_POST['Bank']))
		{
			$cekFile=$model->logo=  CUploadedFile::getInstance($model, 'logo');
			if (empty($cekFile)) {
				$model->attributes=$_POST['Bank'];
                $model->save();
			} else {
				$model->attributes=$_POST['Bank'];
                $model->logo=  CUploadedFile::getInstance($model, 'logo');
	
				if($model->save()){
					$model->logo->saveAs(Yii::app()->basePath.self::URLUPLOAD.$model->logo.'');			
					$this->redirect(array('view','id'=>$model->id));
				}
			}
		}
		
		/*$model=new Bank;

		if(isset($_POST['Bank']))	{
			$model->attributes=$_POST['Bank'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}*/

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		isAuth::Admin();
		$model=$this->loadModel($id);

 		if(isset($_POST['Bank']))	{
 			$cekFile=$model->logo=  CUploadedFile::getInstance($model, 'logo');
 			if (empty($cekFile)) {
 				$model->attributes=$_POST['Bank'];
                $model->save();
 			} else {
 				$model->attributes=$_POST['Bank'];
                $model->logo=  CUploadedFile::getInstance($model, 'logo');
	            if($model->save())	{
	            	$model->logo->saveAs(Yii::app()->basePath.self::URLUPLOAD.$model->logo.'');
	                $this->redirect(array('view','id'=>$model->id));
	            }
 			}
        }		

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		isAuth::Admin();
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		isAuth::Admin();
		$dataProvider=new CActiveDataProvider('Bank');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		isAuth::Admin();
		$model=new Bank('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Bank']))
			$model->attributes=$_GET['Bank'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Bank the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Bank::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Bank $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='bank-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/bank/_form.php
<?php
/* @var $this BankController */
/* @var $model Bank */
/* @var $form CActiveForm */
?>

<div class="form" style="margin: 10px;">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'bank-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data'),
)); ?>

	<p class="alert alert-warning">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'nama_bank', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'nama_bank',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
		<?php echo $form->error($model,'nama_bank'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'pemilik', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'pemilik',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
		<?php echo $form->error($model,'pemilik'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'no_rek', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'no_rek',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
		<?php echo $form->error($model,'no_rek'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'logo', array('class'=>'label-control')); ?>
		<?php echo $form->fileField($model,'logo',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
		<?php echo $form->error($model,'logo'); ?>
	</div>
	<div class="form-group pull-right">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class'=>'btn btn-primary btn-flat')); ?>
	</div>
	<br><br><br><br>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/bank/_search.php
<?php
/* @var $this BankController */
/* @var $model Bank */
/* @var $form CActiveForm */
?>

<div class="form-group" style="margin: 10px;">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>
 
	<div class="form-group">
		<?php echo $form->label($model,'id', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'id', array('class'=>'form-control')); ?>
	</div>

	<div class="form-group">
		<?php echo $form->label($model,'nama_bank', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'nama_bank',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
	</div>

	<div class="form-group">
		<?php echo $form->label($model,'pemilik', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'pemilik',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
	</div>

	<div class="form-group">
		<?php echo $form->label($model,'no_rek', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'no_rek',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
	</div>

	<div class="form-group">
		<?php echo $form->label($model,'logo', array('class'=>'label-control')); ?>
		<?php echo $form->textField($model,'logo',array('size'=>60,'maxlength'=>100, 'class'=>'form-control')); ?>
	</div>

	<div class="form-group pull-left">
		<?php echo CHtml::submitButton('Search', array('class'=>'btn btn-primary btn-flat')); ?>
	</div>
	<br><br>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/bank/_view.php
<?php
/* @var $this BankController */
/* @var $data Bank */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nama_bank')); ?>:</b>
	<?php echo CHtml::encode($data->nama_bank); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('pemilik')); ?>:</b>
	<?php echo CHtml::encode($data->pemilik); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('no_rek')); ?>:</b>
	<?php echo CHtml::encode($data->no_rek); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('logo')); ?>:</b>
	<?php echo CHtml::encode($data->logo); ?>
	<br />


</div>

protected/views/bank/admin.php
<?php
/* @var $this BankController */
/* @var $model Bank */

$this->breadcrumbs=array(
	'Banks'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Bank', 'url'=>array('index')),
	array('label'=>'Create Bank', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#bank-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<br><br>
<div class="box box-primary">
	<div class="box-header with-border">
      	<h3 class="box-title">Kelola Bank</h3>
		<span style="float: right;padding-top: 15px;">
			<a href="<?php echo Yii::app()->createUrl('bank/index'); ?>" class="btn btn-primary"><i class="fa fa-bars"></i> List Bank Transfer</a>
			<a href="<?php echo Yii::app()->createUrl('bank/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Tambah Bank Transfer</a>
		</span>
	</div>
	<div style="margin: 10px;">
		<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
		<div class="search-form" style="display:none">
		<?php $this->renderPartial('_search',array(
			'model'=>$model,
		)); ?>		
	</div>
	</div><!-- search-form -->	
	<div style="margin: 10px;">
	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'bank-grid',
		'dataProvider'=>$model->search(),
		'filter'=>$model,
		'columns'=>array(
			'id',
			'nama_bank',
			'pemilik',
			'no_rek',
			'logo',
			array(
				'class'=>'CButtonColumn',
			),
		),
	)); ?>		
	</div>	
</div>

protected/views/bank/create.php
<?php
/* @var $this BankController */
/* @var $model Bank */

$this->breadcrumbs=array(
	'Banks'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Bank', 'url'=>array('index')),
	array('label'=>'Manage Bank', 'url'=>array('admin')),
);
?>
<br>
<div class="box box-primary">
	<div class="box-header with-border">
      	<h3 class="box-title">Tambah Bank Transfer</h3>
		<span style="float: right;padding-top: 15px;">
			<a href="<?php echo Yii::app()->createUrl('bank/admin'); ?>" class="btn btn-danger"><i class="fa fa-cogs"></i> Kelola Bank Transfer</a>
			<a href="<?php echo Yii::app()->createUrl('bank/index'); ?>" class="btn btn-primary"><i class="fa fa-bars"></i> List Bank Transfer</a>
		</span>
	</div>
	<?php $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

protected/views/bank/index.php
<?php
/* @var $this BankController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Banks',
);

$this->menu=array(
	array('label'=>'Create Bank', 'url'=>array('create')),
	array('label'=>'Manage Bank', 'url'=>array('admin')),
);
?>

<br><br>

<div class="box box-primary">
	<div class="box-header with-border">
      	<h3 class="box-title">Bank Transfer</h3>
		<span style="float: right;padding-top: 15px;">
			<a href="<?php echo Yii::app()->createUrl('bank/create'); ?>" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Bank Transfer</a>
			<a href="<?php echo Yii::app()->createUrl('bank/admin'); ?>" class="btn btn-danger"><i class="fa fa-cogs"></i> Kelola Bank Transfer</a>
		</span>
	</div>
	
	<div style="margin: 10px;">
		<?php $this->widget('zii.widgets.CListView', array(
			'dataProvider'=>$dataProvider,
			'itemView'=>'_view',
		)); ?>		
	</div>
	<br>
</div>

  

protected/views/bank/update.php
<?php
/* @var $this BankController */
/* @var $model Bank */

$this->breadcrumbs=array(
	'Banks'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Bank', 'url'=>array('index')),
	array('label'=>'Create Bank', 'url'=>array('create')),
	array('label'=>'View Bank', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Bank', 'url'=>array('admin')),
);
?>
 
<br>
<div class="box box-primary">
	<div class="box-header with-border">
      	<h3 class="box-title">Ubah Bank Tranfer <?php echo $model->id; ?></h3>
		<span style="float: right;padding-top: 15px;">
			<a href="<?php echo Yii::app()->createUrl('bank/index'); ?>" class="btn btn-primary" title="List Bank Transfer"><i class="fa fa-bars"></i></a>
			<!-- echo Yii::app()->createUrl('bank/delete/'.$model->id); -->
			<a href="<?php echo Yii::app()->createUrl('bank/'.$model->id); ?>" class="btn btn-info" title="View Bank Transfer"><i class="fa fa-search"></i></a>
			<a href="<?php echo Yii::app()->createUrl('bank/create'); ?>" class="btn btn-success" title="Tambah Bank Transfer"><i class="fa fa-plus"></i></a>
			<a href="<?php echo Yii::app()->createUrl('bank/admin'); ?>" class="btn btn-danger" title="Kelola Bank Transfer"><i class="fa fa-cogs"></i></a>
		</span>
	</div>
	<?php $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

protected/views/bank/view.php
<?php
/* @var $this BankController */
/* @var $model Bank */

$this->breadcrumbs=array(
	'Banks'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Bank', 'url'=>array('index')),
	array('label'=>'Create Bank', 'url'=>array('create')),
	array('label'=>'Update Bank', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Bank', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Bank', 'url'=>array('admin')),
);
?>
<br>  
<div class="box box-primary">
	<div class="box-header with-border">
      	<h3 class="box-title">View Bank #<?php echo $model->id; ?></h3>
		<span style="float: right;padding-top: 15px;">
			<a href="<?php echo Yii::app()->createUrl('bank/index'); ?>" class="btn btn-info" title="List Bank Transfer"><i class="fa fa-bars"></i></a>
			<a href="<?php echo Yii::app()->createUrl('bank/create'); ?>" class="btn btn-primary" title="Tambah Bank Transfer"><i class="fa fa-plus"></i></a>
			<a href="<?php echo Yii::app()->createUrl('bank/update/'.$model->id); ?>" class="btn btn-warning" title="Update Bank Transfer"><i class="fa fa-pencil"></i></a>
			<a href="<?php echo Yii::app()->createUrl('bank/delete/'.$model->id); ?>" class="btn btn-danger" title="Delete Bank Transfer"><i class="fa fa-trash"></i></a>
			<a href="<?php echo Yii::app()->createUrl('bank/admin'); ?>" class="btn btn-success" title="Kelola Bank Transfer"><i class="fa fa-cogs"></i></a>
		</span>
	</div>
	<div style="margin: 10px;">
		<?php $this->widget('zii.widgets.CDetailView', array(
			'data'=>$model,
			'attributes'=>array(
				'id',
				'nama_bank',
				'pemilik',
				'no_rek',
				'logo',
			),
		)); ?>		
	</div>	
	<br>
</div>	