protected/models/Permintaan.php
<?php

/**
 * This is the model class for table "permintaan".
 *
 * The followings are the available columns in table 'permintaan':
 * @property integer $id
 * @property string $tanggal
 * @property string $supplier_id
 * @property string $produk_id
 * @property integer $jumlah
 */
class Permintaan extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'permintaan';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('tanggal, supplier_id, produk_id, jumlah', 'required'),
			array('jumlah', 'numerical', 'integerOnly'=>true),
			array('supplier_id, produk_id', 'length', 'max'=>50),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, tanggal, supplier_id, produk_id, jumlah', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'supplier_relasi'=>array(self::BELONGS_TO, 'Supplier','supplier_id'),

			'product_relasi'=>array(self::BELONGS_TO,'Product','produk_id'),
			// 'brand'=>array(self::BELONGS_TO,'brand','brand_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'tanggal' => 'Tanggal',
			'supplier_id' => 'Supplier',
			'produk_id' => 'Produk',
			'jumlah' => 'Jumlah',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('supplier_id',$this->supplier_id,true);
		$criteria->compare('produk_id',$this->produk_id,true);
		$criteria->compare('jumlah',$this->jumlah);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Permintaan the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/PermintaanController.php
<?php

class PermintaanController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin_page';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','admin','delete','report'),
				'users'=>array('*'),
			),
/*			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),*/
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionReport()
	{
		$model = new Permintaan();
		$rptPdf = array();
		$rptPdf = Permintaan::model()->findAll('id','nama_supplier','product_name');
		$this->render('exportpdf', array('rptPdf' => $rptPdf));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		isAuth::Admin();
		$model=new Permintaan;
		// $product = Product::model()->findAll();

		if(isset($_POST['Permintaan']))
		{
			$model->attributes=$_POST['Permintaan'];
			if($model->save())

				$update = Yii::app()->db->createCommand()
					->update('product',
						array('stock'=>new CDbExpression('stock + :test1', array(':test1'=>$model->jumlah)),
						),
						// array('stock'=>new CDbExpression('stock + :test2', array(':test2'=>$model->jumlah)),),
						'id=:produk_id',
						array(':produk_id'=>$model->produk_id)
					);
				$update = Yii::app()->db->createCommand()
					->update('product',
						array('jumlah_masuk'=>new CDbExpression('jumlah_masuk + :test2', array(':test2'=>$model->jumlah)),
						),
						// array('stock'=>new CDbExpression('stock + :test2', array(':test2'=>$model->jumlah)),),
						'id=:produk_id',
						array(':produk_id'=>$model->produk_id)
					);

				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
			// 'product'=>$product,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Permintaan']))
		{
			$model->attributes=$_POST['Permintaan'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		/*$model = Permintaan::model()->findAll();
		$dataProvider=new CActiveDataProvider('Permintaan');*/

		$sql = "SELECT * FROM permintaan ORDER BY id";
		$cursor = Permintaan::model()->findAllBySql($sql);
		$this->render('index',array(
			'cursor'=>$cursor,
		));
	}

	/**
	 * Manages all models.
	*/
	public function actionAdmin()
	{
		$model=new Permintaan('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Permintaan']))
			$model->attributes=$_GET['Permintaan'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Permintaan the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Permintaan::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Permintaan $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='permintaan-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/permintaan/_form.php
<?php
/* @var $this PermintaanController */
/* @var $model Permintaan */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'permintaan-form',
	'enableAjaxValidation'=>false,
)); ?>

	<!-- <p class="note">Fields with <span class="required">*</span> are required.</p> -->

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<div class="col-md-12">
			<table class="table table-bordered">
				<thead style="width: 100%;">
					<th><?php echo $form->labelEx($model,'tanggal', array('class'=>'label-control')); ?></th>
					<th><?php echo $form->labelEx($model,'supplier_id', array('class'=>'label-control')); ?></th>
				</thead>
				<tbody>
					<tr>
						<td>
							<?php echo $form->textField($model,'tanggal', array('class'=>'form-control', 'value'=>date('Y-m-d'), 'readOnly'=>true)); ?>
							<?php echo $form->error($model,'tanggal'); ?>
						</td>
						<td>
							<?php echo $form->dropDownList($model,'supplier_id',CHtml::listData(Supplier::model()->findAll(), 'id','nama_supplier'), array(
								'empty'=>'Pilih Supplier',
								'class'=>'form-control',
							));
							?>
							<?php echo $form->error($model,'supplier_id'); ?>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>	

	<div class="row">
		<div class="col-md-12">
			<table class="table table-bordered">
				<thead style="width: 100%;">
					<th><?php echo $form->labelEx($model,'produk_id', array('class'=>'label-control')); ?></th>
					<th><?php echo $form->labelEx($model,'jumlah', array('class'=>'label-control')); ?></th>
				</thead>
				<tbody>
					<tr>
						<td>
							<?php echo $form->dropDownList($model,'produk_id',CHtml::listData(Product::model()->findAll(), 'id','product_name'), array('empty'=>'Pilih Produk','class'=>'form-control',));?>
							<?php echo $form->error($model,'produk_id'); ?>
						</td>
						<td>
							<?php echo $form->textField($model,'jumlah', array('class'=>'form-control','placeholder'=>'Jumlah')); ?>
							<?php echo $form->error($model,'jumlah'); ?>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group pull-right">
				<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class'=>'btn btn-primary btn-flat')); ?>				
			</div>
		</div>		
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/permintaan/_search.php
<?php
/* @var $this PermintaanController */
/* @var $model Permintaan */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tanggal'); ?>
		<?php echo $form->textField($model,'tanggal'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'supplier_id'); ?>
		<?php echo $form->textField($model,'supplier_id',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'produk_id'); ?>
		<?php echo $form->textField($model,'produk_id',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'jumlah'); ?>
		<?php echo $form->textField($model,'jumlah'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/permintaan/_view.php
<?php
/* @var $this PermintaanController */
/* @var $data Permintaan */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tanggal')); ?>:</b>
	<?php echo CHtml::encode($data->tanggal); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('supplier_id')); ?>:</b>
	<?php echo CHtml::encode($data->supplier_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('produk_id')); ?>:</b>
	<?php echo CHtml::encode($data->produk_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('jumlah')); ?>:</b>
	<?php echo CHtml::encode($data->jumlah); ?>
	<br />


</div>

protected/views/permintaan/admin.php
<?php
/* @var $this PermintaanController */
/* @var $model Permintaan 

$this->breadcrumbs=array(
	'Permintaans'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Permintaan', 'url'=>array('index')),
	array('label'=>'Create Permintaan', 'url'=>array('create')),
);
*/
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#permintaan-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h3 class="box-title">Kelola Permintaan Produk</h3>
<br>
<div class="box box-primary">
	<div class="box-header">
		<span style="float: right;padding-top: 15px; margin: 5px;">
			<a href="<?php echo Yii::app()->createUrl('permintaan/index'); ?>" class="btn btn-danger btn-flat btn-sm" title="List Permintaaan"><i class="fa fa-bars"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/create'); ?>" class="btn btn-info btn-flat btn-sm" title="Tambah Permintaaan"><i class="fa fa-plus"></i></a>
		</span>
	</div>
	<div style="margin: 10px;">
	<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
	<div class="search-form" style="display:none">
	<?php $this->renderPartial('_search',array(
		'model'=>$model,
	)); ?>
	</div><!-- search-form -->

	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'permintaan-grid',
		'dataProvider'=>$model->search(),
		'pagerCssClass'=>'pagination',
	    'ajaxUpdate'=>true, 
		'filter'=>$model,
		'columns'=>array(
			'id',
			'tanggal',
			array('name'=>'supplier_id',
				'type'=>'html',
				'value'=>'$data->supplier_relasi->nama_supplier',
				'sortable'=>TRUE,
				'filter'=>CHtml::listData(Supplier::model()->findAll(),'id','nama_supplier'),
			),
			array('name'=>'produk_id',
				'type'=>'html',
				'value'=>'$data->product_relasi->product_name',
				'sortable'=>TRUE,
				'filter'=>CHtml::listData(Product::model()->findAll(),'id','product_name'),
			),
			// 'supplier_id',
			// 'produk_id',
			'jumlah',
			array(
				'header'=>'Aksi',
				'class'=>'CButtonColumn',
				'template'=>'{update}{view}{delete}'

			),
		),
	)); ?>
	</div>
</div>

protected/views/permintaan/create.php
<?php
/* @var $this PermintaanController */
/* @var $model Permintaan */
/*
$this->breadcrumbs=array(
	'Permintaans'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Permintaan', 'url'=>array('index')),
	array('label'=>'Manage Permintaan', 'url'=>array('admin')),
);*/
?>

<h3 class="box-title">Permintaan Produk</h3>
<br>
<div class="box box-primary">
	<div class="box-header">
		<span style="float: right;padding-top: 15px; margin: 5px;">
			<a href="<?php echo Yii::app()->createUrl('permintaan/index'); ?>" class="btn btn-info btn-flat btn-sm" title="List Permintaaan"><i class="fa fa-search"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/admin'); ?>" class="btn btn-danger btn-flat btn-sm" title="Kelola Permintaaan"><i class="fa fa-cogs"></i></a>
		</span>
	</div>
	<?php $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

protected/views/permintaan/index.php
<?php
/* @var $this PermintaanController */
/* @var $dataProvider CActiveDataProvider 

$this->breadcrumbs=array(
	'Permintaans',
);

$this->menu=array(
	array('label'=>'Create Permintaan', 'url'=>array('create')),
	array('label'=>'Manage Permintaan', 'url'=>array('admin')),
);*/
?>

<h3 class="box-title">Permintaan Produk</h3>
<br>
<div class="box box-primary">
	<div class="box-header">
		<span style="float: right;padding-top: 15px; margin: 5px;">
			<a href="<?php echo Yii::app()->createUrl('permintaan/create'); ?>" class="btn btn-info btn-flat btn-sm" title="List Permintaaan"><i class="fa fa-plus"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/admin'); ?>" class="btn btn-danger btn-flat btn-sm" title="Kelola Permintaaan"><i class="fa fa-cogs"></i></a>
		</span>
	</div>
	<div style="margin: 10px;">
		<table id="example2" class="table table-bordered">
			<thead>
				<tr style="width: 100%;">
					<th>ID</th>
					<th>Tanggal</th>
					<th>Supplier</th>
					<th>Produk</th>
					<th>Jumlah</th>	
					<th><center>Aksi</center></th>			
				</tr>
			</thead>
			<tbody>
			<?php 
			/*$this->widget('zii.widgets.CListView', array(
				'dataProvider'=>$dataProvider,
				'itemView'=>'_view',
			)); foreach($model as $data):*/ 
			for ($i=0; $i < sizeof($cursor); $i++) { 
				$model = $cursor[$i];
			?>
				<tr style="width: 100%;">
					<td><?php echo $model->id; ?></td>
					<td><?php echo $model->tanggal; ?></td>
					<td><?php echo $model->supplier_relasi->nama_supplier; ?></td>
					<td><?php echo $model->product_relasi->product_name; ?></td>
					<td><?php echo $model->jumlah; ?></td>	
					<td><center>
						<a href="<?php echo $model['id']; ?>" class="btn btn-info btn-flat btn-xs"><i class="fa fa-info fa-sm"></i> Detail</a>
						<a href="<?php echo Yii::app()->request->baseUrl;?>/permintaan/report" class="btn btn-default btn-flat btn-xs"><i class="fa fa-print fa-sm"></i> export</a>
						</center>
					</td>				
				</tr>
			<?php } /*endforeach;*/ ?>
			</tbody>
		</table>
	</div>
	<br>
</div>

protected/views/permintaan/update.php
<?php
/* @var $this PermintaanController */
/* @var $model Permintaan 

$this->breadcrumbs=array(
	'Permintaans'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Permintaan', 'url'=>array('index')),
	array('label'=>'Create Permintaan', 'url'=>array('create')),
	array('label'=>'View Permintaan', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Permintaan', 'url'=>array('admin')),
);*/
?>

<h3 class="box-title">Update Permintaan #<?php echo $model->id; ?></h3>
<br>
<div class="box box-primary">
	<div class="box-header">
		<span style="float: right;padding-top: 15px; margin: 5px;">
			<a href="<?php echo Yii::app()->createUrl('permintaan/index'); ?>" class="btn btn-info btn-sm btn-flat" title="List Permintaan"><i class="fa fa-cogs"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/create'); ?>" class="btn btn-primary btn-sm btn-flat" title="Create Permintaan"><i class="fa fa-plus"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/view', array('id'=>$model->id)); ?>" class="btn btn-success btn-sm btn-flat" title="Lihat Permintaan"><i class="fa fa-search"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/admin'); ?>" class="btn btn-danger btn-sm btn-flat" title="Kelola Permintaan"><i class="fa fa-edit"></i></a>
		</span>
	</div>
	<?php $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

protected/views/permintaan/view.php
<?php
/* @var $this PermintaanController */
/* @var $model Permintaan 

$this->breadcrumbs=array(
	'Permintaans'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Permintaan', 'url'=>array('index')),
	array('label'=>'Create Permintaan', 'url'=>array('create')),
	array('label'=>'Update Permintaan', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Permintaan', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Permintaan', 'url'=>array('admin')),
); */
?>

<h1>Detail Permintaan Produk #<?php echo $model->id; ?></h1>

<br>
<div class="box box-primary">
	<div class="box-header">
		<span style="float: right;padding-top: 15px; margin: 5px;">
			<a href="<?php echo Yii::app()->createUrl('permintaan/index'); ?>" class="btn btn-info btn-flat btn-sm" title="List Permintaaan"><i class="fa fa-bars"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/create'); ?>" class="btn btn-success btn-flat btn-sm" title="Tambah Permintaaan Produk"><i class="fa fa-plus"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/update', array('id'=>$model->id)); ?>" class="btn btn-warning btn-flat btn-sm" title="Update Permintaaan Produk"><i class="fa fa-edit"></i></a>
			<a href="<?php echo Yii::app()->createUrl('permintaan/admin'); ?>" class="btn btn-danger btn-flat btn-sm" title="Kelola Permintaaan"><i class="fa fa-cogs"></i></a>
		</span>
	</div>
	<div style="margin: 10px;">
		<?php $this->widget('zii.widgets.CDetailView', array(
			'data'=>$model,
			'attributes'=>array(
				'id',
				'tanggal',
				array(
					'value' => $model->supplier_relasi->nama_supplier, 
					'label' => 'Nama Supplier'
				),
				array(
					'value' => $model->product_relasi->product_name, 
					'label' => 'Nama Produk'
				),
				'jumlah',
			),
		)); ?>
	</div>
	<br>
</div>